Repository jenkinsci/configurationslicing-plugin, pull requests merged in 2024-10, with the labels that each got.

#281 Require Jenkins 2.452.4 or newer
  pom.xml
Labels: chore

#282 add findsecbugs
  pom.xml
Labels: chore

#284 Link to changelog from README
  CHANGELOG.adoc
  README.adoc
  configurationslicing.iml
  mvnvm.properties
Labels: documentation

#285 Convert JUnit3 to JUnit4
  src/test/java/configurationslicing/ChronSplittingTest.java
  src/test/java/configurationslicing/EmailSlicerTest.java
  src/test/java/configurationslicing/JdkSlicerTest.java
  src/test/java/configurationslicing/LogRotationSlicerTest.java
  src/test/java/configurationslicing/PythonTest.java
  src/test/java/configurationslicing/ShellTest.java
  src/test/java/configurationslicing/TimerSliceStringSlicerTest.java
  src/test/java/configurationslicing/claim/ClaimSlicerTest.java
  src/test/java/configurationslicing/maven/MavenSnapshotBuildTriggerTest.java
Labels: test

#289 start of internationalization of plugin
  src/main/java/configurationslicing/ConfigurationSlicing.java
  src/main/java/configurationslicing/UnorderedStringSlicer.java
  src/main/java/configurationslicing/tools/AntSlicer.java
  src/main/resources/configurationslicing/Messages.properties
  src/main/resources/configurationslicing/Messages_it.properties
  src/main/resources/configurationslicing/tools/Messages.properties
Labels: hacktoberfest

#290 Require Jenkins 2.479
  pom.xml
  src/main/java/configurationslicing/AbstractJob.java
  src/main/java/configurationslicing/ConfigurationSlicing.java
  src/main/java/configurationslicing/buildtimeout/BuildTimeoutSlicer.java
  src/main/java/configurationslicing/customworkspace/CustomWorkspaceStringSlicer.java
  src/main/java/configurationslicing/executeshell/AbstractBuildCommandSlicer.java
  src/main/java/configurationslicing/logstash/LogStashSlicer.java
  src/main/java/configurationslicing/maven/MavenVersionSlicer.java
  src/main/java/configurationslicing/parameters/ParametersSlicer.java
  src/main/java/configurationslicing/pipeline/PipelineScriptSlicer.java
  src/main/java/configurationslicing/timer/SCMTimerSliceStringSlicer.java
Labels: chore

#293 Require Jenkins 2.479.1 or newer
  pom.xml
Labels: chore
